# config/routes.yaml

# Charger automatiquement les routes des contrôleurs via les attributs
controllers:
    resource: ../src/Controller/
    type: attribute

# Route personnalisée pour la page de connexion
app_login:
    path: /login
    controller: App\Controller\AuthController::login

# Route personnalisée pour la page d'inscription
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register